// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3bUV4xLAKFRb9ZnBl34iCBxmGua2qX1w',
    appId: '1:705651446013:web:b36b99218662d087f1ae94',
    messagingSenderId: '705651446013',
    projectId: 'first-app-92f21',
    authDomain: 'first-app-92f21.firebaseapp.com',
    databaseURL:
        'https://first-app-92f21-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-92f21.appspot.com',
    measurementId: 'G-MG88QWV9WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXPxO2uLF5UM96ctyY-gk28t_u4URCWc4',
    appId: '1:705651446013:android:f1649fb67b3c417cf1ae94',
    messagingSenderId: '705651446013',
    projectId: 'first-app-92f21',
    databaseURL:
        'https://first-app-92f21-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-92f21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD76mLzc0jZ2oL8urn57OwXqfO6ewYWYYI',
    appId: '1:705651446013:ios:646dcf8e688b3856f1ae94',
    messagingSenderId: '705651446013',
    projectId: 'first-app-92f21',
    databaseURL:
        'https://first-app-92f21-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-92f21.appspot.com',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD76mLzc0jZ2oL8urn57OwXqfO6ewYWYYI',
    appId: '1:705651446013:ios:d1c80c11105e703af1ae94',
    messagingSenderId: '705651446013',
    projectId: 'first-app-92f21',
    databaseURL:
        'https://first-app-92f21-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-92f21.appspot.com',
    iosBundleId: 'com.example.daftarBelanja.RunnerTests',
  );
}
